services:
  db-inventario:
    image: postgres:latest
    container_name: postgres-inventario
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventario_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_inventario:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-inventario
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    restart: always

volumes:
  pgdata_inventario:
